### ISSUE TITLE
Insertion of new cell values does not work

### ISSUE THREAD

**Issue by gro1729** [michal-h21/odsfile#14]
I tried the below standing LaTeX-File (beispiel.ods contains one line with two columns). The File compiles with

`lualatex --shell-escape --synctex=1 beispiel.tex
`
 
but the contents of the ods- File is not modified. Some help would be great.

```
\usepackage{lmodern,odsfile,booktabs}

\begin{document}
   \loadodsfile{beispiel.ods}
   
   \includespread[template=booktabs, columns=head]
   \begin{AddRow}[2]
      \AddString{Hello}{1}
      \AddNumber{42}{2}
   \end{AddRow}
   
   \savespreadsheet
   \includespread[template=booktabs, columns=head]
\end{document}

```
[beispiel.ods](https://github.com/michal-h21/odsfile/files/12503393/beispiel.ods)

**Comment by michal-h21** [comment]
Thanks for the report. This feature was completely broken, no data were saved. It should be fixed in the latest commit.
