### ISSUE TITLE
rows with text are not printed

### ISSUE THREAD

**Issue by u-fischer** [michal-h21/odsfile#6]
I played around with odsfile (installed with TL2015) and a simple ods file created by LibreOffice.  (I can't attach it).  I have the problem that rows at the top of a table which contain only text cells sometimes doesn't  appear. E.g. 

```
abc      abc
world   from
```

outputs only "world from". The tabular line itself is there, but it has no content.

On the other hand 

```
abc
world    from
```

works fine. 

The code I used:

```
\documentclass{article}
\usepackage{fontspec}
\usepackage{odsfile}

\begin{document}

x\begin{tabular}[t]{llllll}
\includespread[file=simple-letter.ods]
\end{tabular}

Tabelle 2

x\begin{tabular}[t]{llll}
\includespread[sheet=Tabelle2]
\end{tabular}

\end{document}
```

![odstest2](https://cloud.githubusercontent.com/assets/4047173/9704341/0c33a8d8-54a4-11e5-97cb-f2fdebb64063.PNG)

**Comment by michal-h21** [comment]
Hi Ulrike, 
Excerpts from u-fischer's message of 2015-09-06 14:33:19 +0200:
> I played around with odsfile (installed with TL2015) and a simple ods
> file created by LibreOffice.  (I can't attach it).  I have the problem
> that rows at the top of a table which contain only text cells
> sometimes doesn't  appear. E.g. 
> 

the most recent changes in Odsfile aren't on CTAN yet, could you please
test the Github version, or send me the problematic file
(michal.h21@gmail.com)? 

Michal

**Comment by u-fischer** [comment]
Hello Michal,,

> Hi Ulrike,
> Excerpts from u-fischer's message of 2015-09-06 14:33:19 +0200:
>> I played around with odsfile (installed with TL2015) and a simple ods
>> file created by LibreOffice.  (I can't attach it).  I have the problem
>> that rows at the top of a table which contain only text cells
>> sometimes doesn't  appear. E.g. 
>> 
>  
> the most recent changes in Odsfile aren't on CTAN yet, could you please
> test the Github version,

With the master version I get the same (wrong) output (see attached zip with
the ods).

The devel version gives a luatex error:


! LuaTeX error [\directlua]:1: 'end' expected near <eof>.
\luacode@dbg@exec ...code@maybe@printdbg {#1} #1 }
                                                  
l.9 \includespread[file=simple-letter.ods]
                                        
? x





-- 
Mit freundlichen Grüßen
Ulrike Fischer
mailto:news3@nililand.de

**Comment by michal-h21** [comment]
Hello Ulrike,

> Hello Michal,,
> 
> > Hi Ulrike,
> > Excerpts from u-fischer's message of 2015-09-06 14:33:19 +0200:
> >> I played around with odsfile (installed with TL2015) and a simple ods
> >> file created by LibreOffice.  (I can't attach it).  I have the problem
> >> that rows at the top of a table which contain only text cells
> >> sometimes doesn't  appear. E.g. 
> >> 
> >  
> > the most recent changes in Odsfile aren't on CTAN yet, could you please
> > test the Github version,
> 
> With the master version I get the same (wrong) output (see attached zip with
> the ods).

It seems that the zip file was blocked, could you please send it again?

> 
> The devel version gives a luatex error:
> 
> 
> ! LuaTeX error [\directlua]:1: 'end' expected near <eof>.
> \luacode@dbg@exec ...code@maybe@printdbg {#1} #1 }
>                                                   

The devel version is abandoned, the most recent is Master branch.

Michal
