### ISSUE TITLE
odsfile does not trigger -recorder output, needed for latexmk

### ISSUE THREAD

**Issue by TPolzer** [michal-h21/odsfile#7]
A simple fix would be to execute `io.open` once without actually using the result. I do not know if there is a better solution (lua/TeX is definitely not my area of expertise).

**Comment by michal-h21** [comment]
Thanks for the tip, `io.open` seems to do the trick. I was not even aware that it is possible to track files opened from Lua with `-recorder`.

**Comment by michal-h21** [comment]
I hope we can close this now.
