### ISSUE TITLE
Feature Request : \cellcomand{range}{LaTeX-Commands[#]}

### ISSUE THREAD

**Issue by TKaluza** [michal-h21/odsfile#8]
First of all thank you very very much for this great package. I do love it. So please see this feature request as a very kind question without any bad background.

Perhaps I am missing something here, but I don't think it is yet possible to do the following:
![image](https://cloud.githubusercontent.com/assets/17787801/22639517/b10a2146-ec4e-11e6-8a87-734e967361ea.png)

(this is a ugly table but I do need it this way, ...)
So if I put it into latex the first row is understandably not rotated. 
![image](https://cloud.githubusercontent.com/assets/17787801/22639475/8b205efa-ec4e-11e6-8421-1e61f387a5a2.png)

### Therefore my feature request is this:
`\cellcomand{range}{LaTeX-Commands[#]}`  ---> `\cellcomand{b1:j1}{\rotatebox{60}{#}}`

Then everything inside a cell is # and therefore rotated, because the LaTeX-Command is insered.

Thank you very much!

**Comment by TKaluza** [comment]
Ok, I think a have not seen a feature of your package - I'm sorry. But I just right now I'm also not able to get it working:
```
\tabletemplate{turning}{%
	\begin{tabular}{-{coltypes}}
		\toprule
		\multicolumn{1}{R{3cm}}{-{colheading}}
		\midrule
		-{content}
		\\ \bottomrule
	\end{tabular}
}
\begin{table}
%\begin{tabular}{l *{9}{c}} %This shouldn't be needed, should it?
	\tiny
	\includespread[file=tab_gewichtung.ods,columns=head,template=turning, sheet=auswertung,range=a1:j10, coltypes=lccccccccc]
%\end{tabular}
\end{table}
```

If I succed I'll update this post

**Comment by michal-h21** [comment]
Hi Tim,

thank you for your kind words and sorry for a late reply. I figured out that what you want isn't possible with current `odsfile` features, so I've added new option for `\includespread` command, `celltemplate`.

It can be used in the following way:

```
\documentclass{article}

\usepackage{graphicx}
\usepackage{odsfile}
\def\rotate#1{\rotatebox{90}{#1}}
\begin{document}
\begin{tabular}{lll}
  \includespread[file=pokus.ods,range=a1:c1,celltemplate={\rotate{-{value}}}] 
  \includespread[range=a2:c]
\end{tabular}
\end{document}

```

It isn't possible to use it with template for the whole table, resp. it is, but you would need to provide some sophisticated LaTeX macro which would rotate only the first row cells. For simplicity, I would use two `\includespread` commands, first to insert the rotated header, the second for the rest of the table.

![snimek z 2017-02-09 15 54 29](https://cloud.githubusercontent.com/assets/504800/22788500/420d879e-eee0-11e6-9a65-56455d8c8255.png)

**Comment by TKaluza** [comment]
Your solution works :100: . Thank you very much. 

So only thing I did not understand is all was fine with my table and your settings in a MWE but in my actual working it does not work. The text is not turned and it but a 0 in front of every part of that table. 
I used now a minipage instead of \rotatebox (don't know what was the conflict here)

Perhaps I did made it too complex, but I'm already have used this code. It helps for line breaks :+1: 

So here seems to be a problemo:
## MWE Example
```
\usepackage{booktabs}
\usepackage{graphicx}
\usepackage{odsfile}
\usepackage{tabularx}
\usepackage{rotating} % gedrehte TabellenÜberschriften
\newcolumntype{R}[1]{>{\begin{turn}{90}\begin{minipage}{#1}\small}l% Hier größe Ändern{\tiny }
			<{\end{minipage}\end{turn}}	}

\begin{document}
	\begin{tabular}{ *{3}{l}}
	%	\toprule 
		\includespread[file=pokus.ods, range=a2:c2, celltemplate={\multicolumn{1}{R{4.5cm}}{-{value}}}]
	%	\midrule 
		\includespread[file=pokus.ods, range=a3:c4] 
	%	\bottomrule 
	\end{tabular}
\end{document}
```

## Error:
`Misplaced \omit. ...plate={\multicolumn{1}{R{4.5cm}}{-{value}}}]`

**Comment by michal-h21** [comment]
It seems that the issue is caused by `\multicolumn`. What about this:

```
\documentclass{article}
\usepackage{booktabs}
\usepackage{graphicx}
\usepackage{odsfile}
\usepackage{tabularx}
\usepackage{rotating} % gedrehte TabellenÜberschriften
\newcolumntype{R}[1]{>{\begin{turn}{90}\begin{minipage}{#1}\small}l% Hier größe Ändern{\tiny }
			<{\end{minipage}\end{turn}}	}

\newcommand\myturn[1]{\begin{turn}{90}\begin{minipage}{4.5cm}\small#1\end{minipage}\end{turn}}
\begin{document}
	\begin{tabular}{ *{3}{l}}
	%	\toprule 
    \includespread[file=pokus.ods, range=a2:c2, celltemplate={\myturn{-{value}}}]
    % \includespread[file=pokus.ods, range=a2:c2, celltemplate={\multicolumn{1}{R{4.5cm}}{-{value}}}]
	%	\midrule 
		\includespread[ range=a3:c4] 
	%	\bottomrule 
	\end{tabular}
\end{document}

```
